server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path('about/', views.about, name='about'),

    # path for contact us view
    path('contact/', views.contact, name='contact'),

    # path for registration
    path('registration/', views.registration_request, name='registration'),

    # path for login
    path('login/', views.login_request, name='login'),

    # path for logout
    path('logout/', views.logout_request, name='logout'),

    path('', views.get_dealerships, name='index'),

    # path for dealer reviews view
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),

    # path for add a review view
    path('review/<int:dealer_id>/', views.add_review, name='add_review')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
import datetime
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):
    name = models.CharField(null=False, max_length=30, default='car make')
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name

class CarModel(models.Model):
    SEDAN = 'sedan'
    SUV = 'SUV'
    WAGON = 'wagon'
    PICKUP = 'pickup'
    TYPE_CHOICES = [
        (SEDAN, 'Sedan'),
        (SUV, 'SUV'),
        (WAGON, 'Wagon'),
        (PICKUP, 'Pickup')
    ]
    YEAR_CHOICES = [(r,r) for r in range(1990, datetime.date.today().year+1)]
    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    name = models.CharField(null=False, max_length=30, default='car model')
    dealer_id = models.IntegerField()
    _type = models.CharField(null=False, max_length=30, choices=TYPE_CHOICES)
    year = models.DateField()

    def __str__(self):
        return "Name: " + self.name 
                #"Make: " + self.car_make + \
                #"Dealer ID: " + self.dealer_id + \
                #"Type: " + self._type + \
                #"Year: " + self.year

class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name

class DealerReview:
    def __init__(self, dealership, name, purchase, review, purchase_date, car_make, car_model, car_year, sentiment, id):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.id = id
        self.review = review
        self.ourchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment

    def __str__(self):
        return "Review :" + self.review + \
                "Name: " + self.name + \
                "Sentiment: " + self.sentiment

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarMake, CarModel, CarDealer
from .restapis import get_dealers_from_cf, get_request, get_dealer_reviews_from_cf, post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
# def about(request):
def about(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
#def contact(request):
def contact(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request
# def login_request(request):
def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
        else:
            return render(request, 'djangoapp/login.html', context)
    else:
        return render(request, 'djangoapp/login.html', context)

# Create a `logout_request` view to handle sign out request
# def logout_request(request):
def logout_request(request):
    print("Log out the user `{}`".format(request.user.username))
    logout(request)
    return redirect('djangoapp:index')

# Create a `registration_request` view to handle sign up request
# def registration_request(request):
# ...
def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.debug("{} is new user".format(username))
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("djangoapp:index")
        else:
            return render(request, 'djangoapp/registration.html', context)


# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://7dc9cbcd.us-south.apigw.appdomain.cloud/capstone/get_dealerships"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)
        context["dealerships"] = dealerships
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    url = "https://7dc9cbcd.us-south.apigw.appdomain.cloud/capstone/reviews"
    context = {}
    params=dict()
    params["dealership"] = dealer_id
    dealer_details = get_dealer_reviews_from_cf(url,kwargs=params)
    context["dealer_details"] = dealer_details
    context["dealer_id"] = dealer_id
    context["dealer_name"] = get_dealers_from_cf("https://7dc9cbcd.us-south.apigw.appdomain.cloud/capstone/get_dealerships")[dealer_id-1].full_name
    return render(request, 'djangoapp/dealer_details.html', context)


# Create a `add_review` view to submit a review
def add_review(request, dealer_id):
    url = "https://7dc9cbcd.us-south.apigw.appdomain.cloud/capstone/reviews"
    if request.method == 'GET':
        url = "https://7dc9cbcd.us-south.apigw.appdomain.cloud/capstone/get_dealerships"
        context = {}
        context["dealer_id"] = dealer_id
        context["dealer_name"] = get_dealers_from_cf(url)[dealer_id-1].full_name
        context["cars"]=CarModel.objects.all()
        return render(request, 'djangoapp/add_review.html', context)
    elif request.method == 'POST':
        if (request.user.is_authenticated):
            review = dict()
            review["name"]=request.POST.get("name")
            review["dealership"]=dealer_id
            review["review"]=request.POST.get("content")
            if ("purchasecheck" in request.POST):
                review["purchase"]=True
            else:
                review["purchase"]=False
            if review["purchase"] == True:
                car=request.POST["car"].split(",")
                review["purchase_date"]=request.POST.get("purchase_date")
                review["car_make"]=car[0]
                review["car_model"]=car[1]
                review["car_year"]=car[2]

            else:
                review["purchase_date"]=None
                review["car_make"]=None
                review["car_model"]=None
                review["car_year"]=None

            json_payload = dict()
            json_payload["review"] = review
            result = post_request(url, json_payload, dealerId=dealer_id)

        return redirect("djangoapp:dealer_details", dealer_id=dealer_id)
    

    

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body>
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Dealership Review</a>
                    <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                    <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">Hi {{ user.first_name }}!</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Username" name="username">
                                <input type="password" class="form-control" placeholder="Password" name="psw">
                                <button class="btn btn-primary" type="submit">Login</button>
                                <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                            </div>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <p class="lead mt-5 text-center">
            <b>Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
        </p>
    </body>

</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
    <body>
        <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Dealership Review</a>
            </div>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">Hi {{ user.first_name }}!</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:about' %}">About</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                    </li>
                    {% else %}
                    <li>
                        <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group">
                                <a class="btn btn-link" href="{% url 'djangoapp:about' %}">About</a>
                                <a class="btn btn-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                                <input type="text" class="form-control" placeholder="Username" name="username" >
                                <input type="password" class="form-control" placeholder="Password" name="psw" >
                                <button class="btn btn-primary" type="submit">Login</button>
                                <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                            </div>
                        </form>
                    </li>
                    {% endif %}
                </ul>
        </div>
    </nav>
        <form action="{% url 'djangoapp:add_review' dealer_id %}"  method="post">
            {% csrf_token %}
            <h2 class="text-left">Review for <b>{{dealer_name}}</b></h2>
            <label for="content"><b>Type your review:</b></label>
            <textarea class="form-control" id="content" name="content" rows="2" required></textarea><br>
            <label for="purchasecheck">Made a purchase at {{dealer_name}}</label>
            <label class="text-white" for="purchasecheck">___</label>
            <input class="form-check-input" float=left type="checkbox" name="purchasecheck" id="purchasecheck"><br>
            <label for="car"><b>Which car did you buy?</b> (If purchased)</label><br>
            <select name="car" id="car" class="form-select" required>
                {% for car in cars %}
                    <option selected value="{{car.car_make}},{{car.id}},{{ car.year}}">{{car.car_make}}-{{car.name}}-{{ car.year|date:"Y" }}</option>
                {% endfor %}
           </select><br><br>
           <label for="purchase_date"><b>Select Your Purchase Date:</b></label>
           <input class="date-own form-control w-25" type="text" name="purchase_date" id="purchase_date"><br>
           <button class="btn btn-primary" type="submit">Submit Review</button>
    </body>
    <script type="text/javascript">
        $('.date-own').datepicker({
           format: 'mm/dd/yyyy'
         });
   </script>
</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>
        <meta charset="UTF-8">
        <title>Dealership Review</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

    </head>

    <body>
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Dealership Review</a>
                    <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                    <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">Hi {{ user.first_name }}!</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Username" name="username">
                                <input type="password" class="form-control" placeholder="Password" name="psw">
                                <button class="btn btn-primary" type="submit">Login</button>
                                <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                            </div>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <p class="mt-5 h1 text-center">
            Contacts us via email at Waka@flaka.com
        </p>
        <ol class="mt-5 h1 text-center">
            <ul><b>Dealer Name:</b> Waka Flaka Flute</ul>
            <ul><b>Phone No:</b> 1 234 567 8999</ul>
            <ul><b>Address:</b> 722 Street, Miami, USA</ul>
        </ol>
    </body>

</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

    <body>

     <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Dealership Review</a>
                <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">Hi {{ user.first_name }}!</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'djangoapp:add_review' dealer_id %}"><b>Add a review here!</b></a>
                    </li>
                    {% else %}
                    <li>
                        <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Username" name="username">
                                <input type="password" class="form-control" placeholder="Password" name="psw">
                                <button class="btn btn-info" type="submit">Login</button>
                                <a class="btn btn-light" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                            </div>
                        </form>
                    </li>
                    {% endif %}
                </ul>
        </div>
    </nav>

        {% if dealer_details %}
        <div class="card-columns">
            {% for review in dealer_details %}
                <div class="card text-dark bg-light mb-3 text-left">
                    <div class="card-header">{{review.name}} ({{ user.username }})</div>
                    <img class="card-img-left" src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png">                 
                    <div class="card-body">
                        <h5 class="card-title">{{review.car_make}}, {{review.car_model}}</h5>
                        <h5 class="card-title">{{review.car_year}}</h5>
                        <p class="card-text">{{review.review}}</p>
                    </div>
                </div>   
            {% endfor %}
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title text-center" width="200">How was your experience?</h5>
                </div>
            {% if user.is_authenticated %}
                
            {% else %}
                <a class="btn btn-link" href="{% url 'djangoapp:login' %}" width="200">Login to write a review</a>
            {% endif %}


        {% else %}
        <div class="card">
            <div class="card-header">
                <h3 class="card-title text-center">Currently No Reviews!</h3>
            </div>
            {% if user.is_authenticated %}
            <a class="btn btn-light" href="{% url 'djangoapp:add_review' dealer_id %}">Write a Review!</a>
            {% else %}
            <a class="btn btn-link" href="{% url 'djangoapp:login' %}">Login to write a review</a>
            {% endif %}
            </div>
        {% endif %}

    <!-- Add reviews as cards -->

    </body>

</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Dealership Review</a>
                <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">Hi {{ user.first_name }}!</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username">
                            <input type="password" class="form-control" placeholder="Password" name="psw">
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!--Add a dealer table here -->
    <div class="container">
    <table class="table" id="table" data-filter-control="true">
            <thead>
                <tr>
                    <th data-field="id">ID</th>
                    <th data-field="full_name">Dealer Name</th>
                    <th data-field="city">City</th>
                    <th data-field="address">Address</th>
                    <th data-field="zip">Zip</th>
                    <th data-field="state" data-filter-control="select">State</th>
                </tr>
            </thead>
            <tbody>
                {% for dealer in dealerships %}
                <tr>
                    <td>{{dealer.id}}</td>
                    <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                    <td>{{dealer.city}}</td>
                    <td>{{dealer.address}}</td>
                    <td>{{dealer.zip}}</td>
                    <td>{{dealer.st}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>

    </body>
    <script>
    $(function() {
        $('#table').bootstrapTable()
    })
  </script>

</html>

server/djangoapp/templates/djangoapp/login.html
<!DOCTYPE html>
<html lang="en">
    <html>
        <head>
            <meta charset="UTF-8">
            {% load static %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        </head>
        <body>
           <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand text-dark" href="#">Dealership Review</a>
                </div>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li>
                            <a class="navbar-brand" href="#">Hi {{ user.first_name }}!</a>
                            <a class="navbar-brand" href="{% url 'djangoapp:logout' %}">Logout</a>
                            <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About</a>
                            <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                        </li>
                        {% else %}
                        <li>
                            <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                                {% csrf_token %}
                                <div class="input-group">
                                    <a class="btn btn-light" href="{% url 'djangoapp:about' %}">About</a>
                                    <a class="btn btn-light" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                                    <input type="text" class="form-control" placeholder="Username" name="username" >
                                    <input type="password" class="form-control" placeholder="Password" name="psw" >
                                    <button class="btn btn-info" type="submit">Login</button>
                                    <a class="btn btn-light" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                                </div>
                            </form>
                        </li>
                        {% endif %}
                    </ul>
            </div>
        </nav>
                <form action="{% url 'djangoapp:login' %}"  method="post">
            {% csrf_token %}
            <div class="container text-center"><br><br>
              <h1>Please Login Using <br> The Form Above.</h1>
                          </div>
                </form>
        </body>
</html>